---
- name: Prepare node
  hosts: k8s
  remote_user: root
  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name:
          - git
          - curl
          - wget
          - tar
          - zip
          - cri-o
        state: present

    - name: Install kubeadm
      ansible.builtin.shell: |
        CNI_PLUGINS_VERSION="v1.3.0"
        ARCH="amd64"
        DEST="/opt/cni/bin"
        sudo mkdir -p "$DEST"
        curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_PLUGINS_VERSION}/cni-plugins-linux-${ARCH}-${CNI_PLUGINS_VERSION}.tgz" | sudo tar -C "$DEST" -xz
        DOWNLOAD_DIR="/usr/local/bin"
        sudo mkdir -p "$DOWNLOAD_DIR"

        CRICTL_VERSION="v1.31.0"
        ARCH="amd64"
        curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-${ARCH}.tar.gz" | sudo tar -C $DOWNLOAD_DIR -xz

        RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"
        ARCH="amd64"
        cd $DOWNLOAD_DIR
        sudo curl -L --remote-name-all https://dl.k8s.io/release/${RELEASE}/bin/linux/${ARCH}/{kubeadm,kubelet}
        sudo chmod +x {kubeadm,kubelet}

        RELEASE_VERSION="v0.16.2"
        curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/krel/templates/latest/kubelet/kubelet.service" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | sudo tee /usr/lib/systemd/system/kubelet.service
        sudo mkdir -p /usr/lib/systemd/system/kubelet.service.d
        curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/krel/templates/latest/kubeadm/10-kubeadm.conf" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | sudo tee /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf

      args:
        creates:
          - /usr/local/bin/crictl
          - /usr/local/bin/kubeadm
          - /usr/local/bin/kubelet
    - name: Start crio
      ansible.builtin.service:
        name: crio
        state: started
        enabled: true

    - name: Start kubelet
      ansible.builtin.service:
        name: kubelet
        state: started
        enabled: true

